Update shell script
ImagineThisUCL/ImagineThisDatabase pull request #1
Opened 2021-01-30 13:59 UTC by bbaayezi

There is no need to install postgres on the local machine, you can just execute the `psql` command inside the postgres container and open an interactive shell using `docker exec -it` command.

2021-01-31 08:00 UTC, lukasotocerny approved these changes
LGTM 👍

2021-01-31 18:26 UTC, bbaayezi commented
There may be further changes made to the shell scripts (change DB schema), so I will leave this PR open

2021-02-01 08:29 UTC, lukasotocerny requested changes
I'd generate automatically UUIDs by default and state `NOT NULL` for better readability.

2021-02-01 08:29 UTC, lukasotocerny commented on CreateDB.sql
> +    feedback_id uuid,
I'd add default UUID generation, `feedback_ui uuid NOT NULL DEFAULT gen_random_uuid()` with the extension `pgcrypto` as described [here](https://dba.stackexchange.com/a/223124). Also I'd explicitly add `NOT NULL`, to make it more obvious.

2021-02-01 08:29 UTC, lukasotocerny commented on CreateDB.sql
> +    vote_id uuid,
Same as previous comment

2021-02-01 08:29 UTC, lukasotocerny commented on CreateDB.sql
> +    conversion_id uuid,
Same as previous comment

2021-02-01 20:18 UTC, lukasotocerny approved these changes
LGTM

2021-02-01 20:37 UTC, merged